name: Release Checks

on:
  # Trigger analysis when pushing to your main branches, and when creating a pull request.
  push:
    branches:
      - 'release/**'

jobs:
  release-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check if version has been updated
      id: check
      uses: EndBug/version-check@v2
      with:
        diff-search: true
        file-name: ./packages/yoroi-extension/package.json
    - name: Log when version changed
      if: steps.check.outputs.changed == 'true'
      run: 'echo "Version change found in commit ${{ steps.check.outputs.commit }}! New version: ${{ steps.check.outputs.version }} (${{ steps.check.outputs.type }})"'

